### ISSUE TITLE
Builtin HTTP Server

### ISSUE THREAD

**Issue by septs** [estkme/lpac#6]
I want to make a [SPA](https://en.wikipedia.org/wiki/Single-page_application) to configure eUICC card [^chips].

If can, I hope it can be provided [JSON-RPC](https://www.jsonrpc.org) or [RESTful API](https://www.redhat.com/en/topics/api/what-is-a-rest-api).

replace [LPA desktop](https://github.com/Truphone/LPAdesktop), LPA desktop need user use java runtime run the program.

[^chips]: e.g: ST33

**Comment by estkme** [comment]
Your profile shows you are in Shanghai, so I will use Chinese to reply your request. If it is not acceptable, please reply.

lpac暂时不考虑使用内置的HTTP服务器，这对于一个C语言项目来讲是比较沉重的一个依赖。
lpac的直接可执行文件先天使用json作为交互接口，你可以很轻松的将它以CGI的形式移植到任意HTTP服务器上，或者集成到一些高级语言的可执行文件内。
由于lpac实际上要面向Windows Linux macOS Android，甚至在内部repo需要面向MCU、FreeRTOS一类的target，引入一个额外的依赖是非常奢侈且在部分target上是不现实的。
你可以选择go或者rust等方式来进行这个操作
